-- MySQL Script generated by MySQL Workbench
-- Wed Sep 25 13:38:16 2024
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema pizza
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema pizza
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `pizza` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
-- -----------------------------------------------------
-- Schema optica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema optica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `optica` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `pizza` ;

-- -----------------------------------------------------
-- Table `pizza`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizza`.`clientes` (
  `id_cliente` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellido` VARCHAR(45) NOT NULL,
  `codigo_postal` VARCHAR(45) NOT NULL,
  `localidad` INT NOT NULL,
  `provincia` INT NOT NULL,
  `telefono` VARCHAR(20) NOT NULL,
  PRIMARY KEY (`id_cliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pizza`.`tiendas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizza`.`tiendas` (
  `id_tienda` INT NOT NULL,
  `direccion` VARCHAR(45) NOT NULL,
  `codigo_postal` VARCHAR(45) NOT NULL,
  `localidad` VARCHAR(45) NOT NULL,
  `provincia` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_tienda`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pizza`.`empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizza`.`empleados` (
  `id_empleado` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `apellidos` VARCHAR(45) NOT NULL,
  `NIF` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `tienda_id` INT NOT NULL,
  PRIMARY KEY (`id_empleado`),
  INDEX `fk_tienda_idx` (`tienda_id` ASC) VISIBLE,
  INDEX `fk_empleado/tienda_idx` (`tienda_id` ASC) VISIBLE,
  CONSTRAINT `fk_empleado/tienda`
    FOREIGN KEY (`tienda_id`)
    REFERENCES `pizza`.`tiendas` (`id_tienda`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pizza`.`pedidos`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizza`.`pedidos` (
  `id_pedido` INT NOT NULL,
  `fecha/hora` DATETIME NOT NULL,
  `num_productos` INT NOT NULL,
  `total` DECIMAL(5,2) NOT NULL,
  `cliente_id` INT NOT NULL,
  `tienda_id` INT NOT NULL,
  `tipo_pedido` ENUM('Domiclio', 'tienda') NOT NULL,
  `empleado_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`id_pedido`),
  INDEX `fk_pedido_idx` (`cliente_id` ASC) VISIBLE,
  INDEX `fk_tienda_idx` (`tienda_id` ASC) VISIBLE,
  INDEX `fk_pedido/empleado_idx` (`empleado_id` ASC) VISIBLE,
  CONSTRAINT `fk_pedido`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `pizza`.`clientes` (`id_cliente`),
  CONSTRAINT `fk_pedido/empleado`
    FOREIGN KEY (`empleado_id`)
    REFERENCES `pizza`.`empleados` (`id_empleado`),
  CONSTRAINT `fk_tienda`
    FOREIGN KEY (`tienda_id`)
    REFERENCES `pizza`.`tiendas` (`id_tienda`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pizza`.`bebidas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizza`.`bebidas` (
  `id_bebida` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(100) NULL DEFAULT NULL,
  `imagen_producto` BLOB NULL DEFAULT NULL,
  `precio` VARCHAR(45) NOT NULL,
  `pedido_id` INT NOT NULL,
  PRIMARY KEY (`id_bebida`),
  INDEX `fk_bebida/pedido_idx` (`pedido_id` ASC) VISIBLE,
  CONSTRAINT `fk_bebida/pedido`
    FOREIGN KEY (`pedido_id`)
    REFERENCES `pizza`.`pedidos` (`id_pedido`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pizza`.`categorias_pizza`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizza`.`categorias_pizza` (
  `id_categoria` INT NOT NULL,
  `nombre_categoria` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_categoria`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pizza`.`hamburguesas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizza`.`hamburguesas` (
  `id_hamburguesa` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(100) NULL DEFAULT NULL,
  `imagen_producto` BLOB NULL DEFAULT NULL,
  `precio` VARCHAR(45) NOT NULL,
  `pedido_id` INT NOT NULL,
  PRIMARY KEY (`id_hamburguesa`),
  INDEX `fk_hamburguesa/pedido_idx` (`pedido_id` ASC) VISIBLE,
  CONSTRAINT `fk_hamburguesa/pedido`
    FOREIGN KEY (`pedido_id`)
    REFERENCES `pizza`.`pedidos` (`id_pedido`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pizza`.`provincias`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizza`.`provincias` (
  `id_provincia` INT NOT NULL,
  `nombre_provincia` VARCHAR(45) NOT NULL,
  `cliente_id` INT NOT NULL,
  PRIMARY KEY (`id_provincia`),
  INDEX `fk_provincia/cliente_idx` (`cliente_id` ASC) VISIBLE,
  CONSTRAINT `fk_provincia/cliente`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `pizza`.`clientes` (`id_cliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pizza`.`localidades`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizza`.`localidades` (
  `id_localidad` INT NOT NULL,
  `nombre_localidad` VARCHAR(45) NOT NULL,
  `provincia_id` INT NOT NULL,
  `cliente_id` INT NOT NULL,
  PRIMARY KEY (`id_localidad`),
  INDEX `fk_locilidades_idx` (`provincia_id` ASC) VISIBLE,
  INDEX `fk_localidad/clientre_idx` (`cliente_id` ASC) VISIBLE,
  CONSTRAINT `fk_localidad/clientre`
    FOREIGN KEY (`cliente_id`)
    REFERENCES `pizza`.`clientes` (`id_cliente`),
  CONSTRAINT `fk_locilidades`
    FOREIGN KEY (`provincia_id`)
    REFERENCES `pizza`.`provincias` (`id_provincia`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `pizza`.`pizzas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `pizza`.`pizzas` (
  `id_pizza` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(100) NULL DEFAULT NULL,
  `imagen_producto` BLOB NULL DEFAULT NULL,
  `precio` VARCHAR(45) NOT NULL,
  `categoria` INT NOT NULL,
  `pedido_id` INT NOT NULL,
  PRIMARY KEY (`id_pizza`),
  INDEX `fk_categoria_idx` (`categoria` ASC) VISIBLE,
  INDEX `fk_pizza/pedido_idx` (`pedido_id` ASC) VISIBLE,
  CONSTRAINT `fk_categoria`
    FOREIGN KEY (`categoria`)
    REFERENCES `pizza`.`categorias_pizza` (`id_categoria`),
  CONSTRAINT `fk_pizza/pedido`
    FOREIGN KEY (`pedido_id`)
    REFERENCES `pizza`.`pedidos` (`id_pedido`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `optica` ;

-- -----------------------------------------------------
-- Table `optica`.`clientes`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`clientes` (
  `id_cliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `codigo_postal` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `correo_electronico` VARCHAR(45) NOT NULL,
  `fecha_registro` DATE NOT NULL,
  `recomendacion` INT NULL DEFAULT NULL,
  `empleado` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_cliente`),
  INDEX `recomendacion_idx` (`recomendacion` ASC) VISIBLE,
  CONSTRAINT `recomendacion`
    FOREIGN KEY (`recomendacion`)
    REFERENCES `optica`.`clientes` (`id_cliente`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `optica`.`empleados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`empleados` (
  `id_empleado` INT NOT NULL,
  `nombre` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_empleado`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `optica`.`proveedores`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`proveedores` (
  `proveedor_id` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(45) NOT NULL,
  `telefono` VARCHAR(45) NOT NULL,
  `fax` VARCHAR(45) NULL DEFAULT NULL,
  `NIF` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`proveedor_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `optica`.`marca`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`marca` (
  `id_marca` INT NOT NULL,
  `proveedor_id` INT NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_marca`),
  CONSTRAINT `proveedor_id`
    FOREIGN KEY (`id_marca`)
    REFERENCES `optica`.`proveedores` (`proveedor_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `optica`.`gafas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`gafas` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `marca_id` INT NOT NULL,
  `graduacion` VARCHAR(45) NOT NULL,
  `montura` VARCHAR(45) NOT NULL,
  `color_montura` VARCHAR(45) NOT NULL,
  `color_vidrios` VARCHAR(45) NULL DEFAULT NULL,
  `precio` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `marca_fk_idx` (`marca_id` ASC) VISIBLE,
  CONSTRAINT `marca_fk`
    FOREIGN KEY (`marca_id`)
    REFERENCES `optica`.`marca` (`id_marca`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `optica`.`ventas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `optica`.`ventas` (
  `idventas` INT NOT NULL,
  `empleado` INT NOT NULL,
  `cliente` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `gafas/producto` INT NOT NULL,
  PRIMARY KEY (`idventas`),
  INDEX `empleado_idx` (`empleado` ASC) VISIBLE,
  INDEX `cliente_idx` (`cliente` ASC) VISIBLE,
  INDEX `gafas_idx` (`gafas/producto` ASC) VISIBLE,
  CONSTRAINT `cliente`
    FOREIGN KEY (`cliente`)
    REFERENCES `optica`.`clientes` (`id_cliente`),
  CONSTRAINT `empleado`
    FOREIGN KEY (`empleado`)
    REFERENCES `optica`.`empleados` (`id_empleado`),
  CONSTRAINT `gafas`
    FOREIGN KEY (`gafas/producto`)
    REFERENCES `optica`.`gafas` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;

USE `pizza`;

DELIMITER $$
USE `pizza`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `pizza`.`pedidos_AFTER_DELETE`
AFTER DELETE ON `pizza`.`pedidos`
FOR EACH ROW
BEGIN

END$$

USE `pizza`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `pizza`.`pedidos_AFTER_INSERT`
AFTER INSERT ON `pizza`.`pedidos`
FOR EACH ROW
BEGIN

END$$

USE `pizza`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `pizza`.`pedidos_AFTER_UPDATE`
AFTER UPDATE ON `pizza`.`pedidos`
FOR EACH ROW
BEGIN

END$$

USE `pizza`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `pizza`.`pedidos_BEFORE_DELETE`
BEFORE DELETE ON `pizza`.`pedidos`
FOR EACH ROW
BEGIN

END$$

USE `pizza`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `pizza`.`pedidos_BEFORE_INSERT`
BEFORE INSERT ON `pizza`.`pedidos`
FOR EACH ROW
BEGIN

END$$

USE `pizza`$$
CREATE
DEFINER=`root`@`localhost`
TRIGGER `pizza`.`pedidos_BEFORE_UPDATE`
BEFORE UPDATE ON `pizza`.`pedidos`
FOR EACH ROW
BEGIN

END$$


DELIMITER ;

SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
